- name: Downloading Redis Repo
  ansible.builtin.package:
    name:   https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state:  present
    disable_gpg_check:  true

- name: Enabling Redis Module
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: Installing Redis
  ansible.builtin.package:
    name: redis
    state:  present

- name: Configuring Redis
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace:  '0.0.0.0'

- name: Enabling And Starting Redis
  ansible.builtin.service:
    name: redis
    state:  restarted
    enabled:  yes